// Expo / React Native project structures — Expo Router uses app/ for routes

const structures = {
  'atomic-design': {
    folders: [
      'components/atoms',
      'components/molecules',
      'components/organisms',
      'components/templates',
      'hooks',
      'stores',
      'services',
      'utils',
      'types',
      'app',
      'assets',
    ],
    componentPath: (name, level) => {
      const levels = {
        atom: 'components/atoms',
        molecule: 'components/molecules',
        organism: 'components/organisms',
        template: 'components/templates',
      };
      return levels[level] || 'components/atoms';
    },
    hookPath: () => 'hooks',
    pagePath: () => 'app',
    servicePath: () => 'services',
    contextPath: () => 'contexts',
    storePath: () => 'stores',
    typePath: () => 'types',
    featurePath: () => 'features',
    schemaPath: () => 'schemas',
    queryPath: () => 'queries',
    guardPath: () => 'guards',
    i18nPath: () => 'i18n',
  },

  'feature-based': {
    folders: [
      'features',
      'components/shared',
      'hooks',
      'stores',
      'services',
      'utils',
      'types',
      'app',
      'assets',
    ],
    componentPath: () => 'components/shared',
    hookPath: () => 'hooks',
    pagePath: () => 'app',
    servicePath: () => 'services',
    contextPath: () => 'contexts',
    storePath: () => 'stores',
    typePath: () => 'types',
    featurePath: () => 'features',
    schemaPath: () => 'schemas',
    queryPath: () => 'queries',
    guardPath: () => 'guards',
    i18nPath: () => 'i18n',
  },

  'domain-driven': {
    folders: [
      'domains',
      'shared/components',
      'shared/hooks',
      'shared/stores',
      'shared/services',
      'shared/utils',
      'shared/types',
      'app',
      'assets',
    ],
    componentPath: () => 'shared/components',
    hookPath: () => 'shared/hooks',
    pagePath: () => 'app',
    servicePath: () => 'shared/services',
    contextPath: () => 'shared/contexts',
    storePath: () => 'shared/stores',
    typePath: () => 'shared/types',
    featurePath: () => 'domains',
    schemaPath: () => 'shared/schemas',
    queryPath: () => 'shared/queries',
    guardPath: () => 'shared/guards',
    i18nPath: () => 'shared/i18n',
  },

  'mvc-like': {
    folders: [
      'views/components',
      'controllers',
      'models',
      'stores',
      'services',
      'utils',
      'types',
      'app',
      'assets',
    ],
    componentPath: () => 'views/components',
    hookPath: () => 'hooks',
    pagePath: () => 'app',
    servicePath: () => 'services',
    contextPath: () => 'contexts',
    storePath: () => 'stores',
    typePath: () => 'models',
    featurePath: () => 'controllers',
    schemaPath: () => 'models',
    queryPath: () => 'services/queries',
    guardPath: () => 'guards',
    i18nPath: () => 'i18n',
  },
};

module.exports = structures;
