const structures = {
  'atomic-design': {
    folders: [
      'components/atoms',
      'components/molecules',
      'components/organisms',
      'components/templates',
      'hooks',
      'contexts',
      'stores',
      'services',
      'utils',
      'types',
      'styles',
    ],
    componentPath: (_name, level) => {
      const levels = {
        atom: 'components/atoms',
        molecule: 'components/molecules',
        organism: 'components/organisms',
        template: 'components/templates',
      };
      return levels[level] || 'components/atoms';
    },
    hookPath: () => 'hooks',
    pagePath: () => 'app',
    servicePath: () => 'services',
    contextPath: () => 'contexts',
    storePath: () => 'stores',
    typePath: () => 'types',
    featurePath: () => 'features',
    apiPath: () => 'app/api',
  },

  'feature-based': {
    folders: [
      'features',
      'components/shared',
      'hooks',
      'contexts',
      'stores',
      'services',
      'utils',
      'types',
      'styles',
    ],
    componentPath: () => 'components/shared',
    hookPath: () => 'hooks',
    pagePath: () => 'features',
    servicePath: () => 'services',
    contextPath: () => 'contexts',
    storePath: () => 'stores',
    typePath: () => 'types',
    featurePath: () => 'features',
    apiPath: () => 'app/api',
  },

  'domain-driven': {
    folders: [
      'domains',
      'shared/components',
      'shared/hooks',
      'shared/contexts',
      'shared/stores',
      'shared/services',
      'shared/utils',
      'shared/types',
      'styles',
    ],
    componentPath: () => 'shared/components',
    hookPath: () => 'shared/hooks',
    pagePath: () => 'domains',
    servicePath: () => 'shared/services',
    contextPath: () => 'shared/contexts',
    storePath: () => 'shared/stores',
    typePath: () => 'shared/types',
    featurePath: () => 'domains',
    apiPath: () => 'app/api',
  },

  'mvc-like': {
    folders: [
      'models',
      'views/components',
      'views/pages',
      'controllers',
      'services',
      'hooks',
      'contexts',
      'stores',
      'utils',
      'types',
      'styles',
    ],
    componentPath: () => 'views/components',
    hookPath: () => 'hooks',
    pagePath: () => 'views/pages',
    servicePath: () => 'services',
    contextPath: () => 'contexts',
    storePath: () => 'stores',
    typePath: () => 'types',
    featurePath: () => 'features',
    apiPath: () => 'app/api',
  },
};

module.exports = structures;
