// Qwik / Qwik City project structures — routes live in src/routes/ (file-based)

const structures = {
  'atomic-design': {
    folders: [
      'src/components/atoms',
      'src/components/molecules',
      'src/components/organisms',
      'src/components/templates',
      'src/hooks',
      'src/stores',
      'src/services',
      'src/utils',
      'src/types',
      'src/routes',
    ],
    componentPath: (name, level) => {
      const levels = {
        atom: 'src/components/atoms',
        molecule: 'src/components/molecules',
        organism: 'src/components/organisms',
        template: 'src/components/templates',
      };
      return levels[level] || 'src/components/atoms';
    },
    hookPath: () => 'src/hooks',
    pagePath: () => 'src/routes',
    servicePath: () => 'src/services',
    contextPath: () => 'src/contexts',
    storePath: () => 'src/stores',
    typePath: () => 'src/types',
    featurePath: () => 'src/features',
    schemaPath: () => 'src/schemas',
    queryPath: () => 'src/queries',
    guardPath: () => 'src/middleware',
    i18nPath: () => 'src/i18n',
  },

  'feature-based': {
    folders: [
      'src/features',
      'src/components/shared',
      'src/hooks',
      'src/stores',
      'src/services',
      'src/utils',
      'src/types',
      'src/routes',
    ],
    componentPath: () => 'src/components/shared',
    hookPath: () => 'src/hooks',
    pagePath: () => 'src/routes',
    servicePath: () => 'src/services',
    contextPath: () => 'src/contexts',
    storePath: () => 'src/stores',
    typePath: () => 'src/types',
    featurePath: () => 'src/features',
    schemaPath: () => 'src/schemas',
    queryPath: () => 'src/queries',
    guardPath: () => 'src/middleware',
    i18nPath: () => 'src/i18n',
  },

  'domain-driven': {
    folders: [
      'src/domains',
      'src/shared/components',
      'src/shared/hooks',
      'src/shared/stores',
      'src/shared/services',
      'src/shared/utils',
      'src/shared/types',
      'src/routes',
    ],
    componentPath: () => 'src/shared/components',
    hookPath: () => 'src/shared/hooks',
    pagePath: () => 'src/routes',
    servicePath: () => 'src/shared/services',
    contextPath: () => 'src/shared/contexts',
    storePath: () => 'src/shared/stores',
    typePath: () => 'src/shared/types',
    featurePath: () => 'src/domains',
    schemaPath: () => 'src/shared/schemas',
    queryPath: () => 'src/shared/queries',
    guardPath: () => 'src/middleware',
    i18nPath: () => 'src/shared/i18n',
  },

  'mvc-like': {
    folders: [
      'src/views/components',
      'src/controllers',
      'src/models',
      'src/stores',
      'src/services',
      'src/utils',
      'src/types',
      'src/routes',
    ],
    componentPath: () => 'src/views/components',
    hookPath: () => 'src/hooks',
    pagePath: () => 'src/routes',
    servicePath: () => 'src/services',
    contextPath: () => 'src/contexts',
    storePath: () => 'src/stores',
    typePath: () => 'src/models',
    featurePath: () => 'src/controllers',
    schemaPath: () => 'src/models',
    queryPath: () => 'src/services/queries',
    guardPath: () => 'src/middleware',
    i18nPath: () => 'src/i18n',
  },
};

module.exports = structures;
