// SvelteKit project structures — routes live in src/routes/ (file-based)

const structures = {
  'atomic-design': {
    folders: [
      'src/lib/components/atoms',
      'src/lib/components/molecules',
      'src/lib/components/organisms',
      'src/lib/components/templates',
      'src/lib/composables',
      'src/lib/stores',
      'src/lib/services',
      'src/lib/utils',
      'src/lib/types',
      'src/routes',
    ],
    componentPath: (name, level) => {
      const levels = {
        atom: 'src/lib/components/atoms',
        molecule: 'src/lib/components/molecules',
        organism: 'src/lib/components/organisms',
        template: 'src/lib/components/templates',
      };
      return levels[level] || 'src/lib/components/atoms';
    },
    hookPath: () => 'src/lib/composables',
    pagePath: () => 'src/routes',
    servicePath: () => 'src/lib/services',
    contextPath: () => 'src/lib/composables',
    storePath: () => 'src/lib/stores',
    typePath: () => 'src/lib/types',
    featurePath: () => 'src/lib/features',
    guardPath: () => 'src/hooks',
    schemaPath: () => 'src/lib/schemas',
    queryPath: () => 'src/lib/queries',
    i18nPath: () => 'src/lib/i18n',
  },

  'feature-based': {
    folders: [
      'src/lib/features',
      'src/lib/components/shared',
      'src/lib/composables',
      'src/lib/stores',
      'src/lib/services',
      'src/lib/utils',
      'src/lib/types',
      'src/routes',
    ],
    componentPath: () => 'src/lib/components/shared',
    hookPath: () => 'src/lib/composables',
    pagePath: () => 'src/routes',
    servicePath: () => 'src/lib/services',
    contextPath: () => 'src/lib/composables',
    storePath: () => 'src/lib/stores',
    typePath: () => 'src/lib/types',
    featurePath: () => 'src/lib/features',
    guardPath: () => 'src/hooks',
    schemaPath: () => 'src/lib/schemas',
    queryPath: () => 'src/lib/queries',
    i18nPath: () => 'src/lib/i18n',
  },

  'domain-driven': {
    folders: [
      'src/lib/domains',
      'src/lib/shared/components',
      'src/lib/shared/composables',
      'src/lib/shared/stores',
      'src/lib/shared/services',
      'src/lib/shared/utils',
      'src/lib/shared/types',
      'src/routes',
    ],
    componentPath: () => 'src/lib/shared/components',
    hookPath: () => 'src/lib/shared/composables',
    pagePath: () => 'src/routes',
    servicePath: () => 'src/lib/shared/services',
    contextPath: () => 'src/lib/shared/composables',
    storePath: () => 'src/lib/shared/stores',
    typePath: () => 'src/lib/shared/types',
    featurePath: () => 'src/lib/domains',
    guardPath: () => 'src/hooks',
    schemaPath: () => 'src/lib/shared/schemas',
    queryPath: () => 'src/lib/shared/queries',
    i18nPath: () => 'src/lib/shared/i18n',
  },

  'mvc-like': {
    folders: [
      'src/lib/views/components',
      'src/lib/controllers',
      'src/lib/models',
      'src/lib/stores',
      'src/lib/services',
      'src/lib/utils',
      'src/lib/types',
      'src/routes',
    ],
    componentPath: () => 'src/lib/views/components',
    hookPath: () => 'src/lib/composables',
    pagePath: () => 'src/routes',
    servicePath: () => 'src/lib/services',
    contextPath: () => 'src/lib/composables',
    storePath: () => 'src/lib/stores',
    typePath: () => 'src/lib/models',
    featurePath: () => 'src/lib/controllers',
    guardPath: () => 'src/hooks',
    schemaPath: () => 'src/lib/models',
    queryPath: () => 'src/lib/services/queries',
    i18nPath: () => 'src/lib/i18n',
  },
};

module.exports = structures;
