const core = require('@actions/core');
const github = require('@actions/github');
const fs = require('fs-extra');
const path = require('path');

// Inline structure maps (same logic as src/commands/stats.js)
const reactStructures = require('../../../src/structures/react');
const nextjsStructures = require('../../../src/structures/nextjs');
const vueStructures = require('../../../src/structures/vue');
const svelteStructures = require('../../../src/structures/svelte');
const solidjsStructures = require('../../../src/structures/solidjs');
const nuxtStructures = require('../../../src/structures/nuxt');

const structureMap = {
  react: reactStructures,
  nextjs: nextjsStructures,
  vue: vueStructures,
  svelte: svelteStructures,
  solidjs: solidjsStructures,
  nuxt: nuxtStructures,
};

async function countFiles(dir) {
  if (!(await fs.pathExists(dir))) return 0;
  let count = 0;
  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.isFile()) count++;
    else if (entry.isDirectory()) count += await countFiles(path.join(dir, entry.name));
  }
  return count;
}

async function run() {
  const cwd = process.env.GITHUB_WORKSPACE || process.cwd();
  const failBelow = parseInt(core.getInput('fail-below') || '100', 10);
  const token = core.getInput('token');

  const configPath = path.join(cwd, '.rchitect.json');
  if (!(await fs.pathExists(configPath))) {
    core.setFailed('.rchitect.json not found. Run "rchitect init" in your project first.');
    return;
  }

  const config = await fs.readJson(configPath);
  const structures = structureMap[config.framework];
  if (!structures) {
    core.setFailed(`Unknown framework "${config.framework}" in .rchitect.json.`);
    return;
  }

  const structure = structures[config.pattern];
  if (!structure) {
    core.setFailed(`Unknown pattern "${config.pattern}" in .rchitect.json.`);
    return;
  }

  const expectedFolders = structure.folders;
  const results = [];
  let presentCount = 0;

  for (const folder of expectedFolders) {
    const fullPath = path.join(cwd, folder);
    const exists = await fs.pathExists(fullPath);
    const fileCount = exists ? await countFiles(fullPath) : 0;
    if (exists) presentCount++;
    results.push({ folder, exists, fileCount });
  }

  const total = expectedFolders.length;
  const compliance = total > 0 ? Math.round((presentCount / total) * 100) : 100;
  const missing = results.filter(r => !r.exists).map(r => r.folder);

  // Set outputs
  core.setOutput('compliance', String(compliance));
  core.setOutput('folders-present', String(presentCount));
  core.setOutput('folders-expected', String(total));

  // Build PR comment
  const statusIcon = compliance === 100 ? '✅' : compliance >= failBelow ? '⚠️' : '❌';
  const rows = results.map(r => `| ${r.exists ? '✅' : '❌'} | \`${r.folder}/\` | ${r.fileCount} |`).join('\n');

  const body = `## ${statusIcon} Rchitect Architecture Check

**Framework:** \`${config.framework}\` &nbsp;|&nbsp; **Pattern:** \`${config.pattern}\`

**Compliance: ${compliance}%** (${presentCount}/${total} folders present)

| Status | Folder | Files |
|--------|--------|-------|
${rows}

${missing.length > 0 ? `> ⚠️ Missing folders: ${missing.map(f => `\`${f}\``).join(', ')}` : '> All expected folders are present.'}

<sub>Generated by [Rchitect](https://github.com/mouawiashride/rchitect)</sub>`;

  // Post PR comment if in a PR context
  if (token && github.context.payload.pull_request) {
    try {
      const octokit = github.getOctokit(token);
      const { owner, repo } = github.context.repo;
      const prNumber = github.context.payload.pull_request.number;

      // Find and update existing comment, or create new one
      const { data: comments } = await octokit.rest.issues.listComments({
        owner, repo, issue_number: prNumber,
      });

      const existing = comments.find(c =>
        c.user && c.user.type === 'Bot' && c.body && c.body.includes('Rchitect Architecture Check')
      );

      if (existing) {
        await octokit.rest.issues.updateComment({ owner, repo, comment_id: existing.id, body });
      } else {
        await octokit.rest.issues.createComment({ owner, repo, issue_number: prNumber, body });
      }
    } catch (err) {
      core.warning(`Failed to post PR comment: ${err.message}`);
    }
  }

  // Log summary
  core.info(`Rchitect compliance: ${compliance}% (${presentCount}/${total} folders)`);
  if (missing.length > 0) {
    core.info(`Missing: ${missing.join(', ')}`);
  }

  if (compliance < failBelow) {
    core.setFailed(`Architecture compliance ${compliance}% is below required ${failBelow}%. Missing: ${missing.join(', ')}`);
  }
}

run().catch(err => core.setFailed(String(err.message || err)));
